routes/web.php
<?php

use App\Http\Controllers\Admin\AdminCalendarController;
use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\User\CalendarController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\User\SavedTaskController;
use App\Http\Controllers\User\UserDashboardController;
use App\Http\Livewire\CompletedTask;
use App\Http\Livewire\User\SavedTasks;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group(['middleware' => 'auth'], function(){

    Route::get('redirects', [HomeController::class, 'index']);

    Route::group(['middleware' => ['role:admin'], 'prefix' => 'admin', 'as' => 'admin.'], function(){
        Route::resource('users', UserController::class);
        Route::get('dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');
        Route::get('calendars', [AdminCalendarController::class,  'index'])->name('calendars');
        Route::get('calendarsEvents', [AdminCalendarController::class,  'fetch']);
    });

    Route::group(['middleware' => ['role:user'], 'prefix' => 'user', 'as' => 'user.'], function(){
        Route::get('dashboard', [UserDashboardController::class, 'index'])->name('dashboard');
        Route::get('completed_task', CompletedTask::class);
        Route::get('saved_tasks', [SavedTaskController::class, 'index'])->name('saved_tasks');
        Route::get('calendars', [CalendarController::class,  'index'])->name('calendars');
        Route::get('calendarsEvents', [CalendarController::class,  'fetch']);
    });

    Route::group(['prefix' => 'notifications', 'as' => 'notifications.'], function () {
        Route::post('/{notification}', [NotificationController::class, 'markNotification'])->name('markNotification');
    });

    Route::resources([
        'clients' => ClientController::class,
        'projects' => ProjectController::class,
        'tasks' => TaskController::class,
    ]);

});

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Project extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'title',
        'description',
        'deadline_at',
        'user_id',
        'client_id',
        'status',
    ];

    public const STATUS = ['open', 'in progress', 'blocked', 'cancelled', 'completed'];

    protected $casts = [
        'deadline_at' => 'datetime:m-d-Y',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    public function tasks()
    {
        return $this->hasMany(Task::class);
    }

    public function getCompletedTasksAttribute()
    {
        return $this->tasks()->where('completed', 1)->count();
    }

    public function getAllTasksAttribute()
    {
        return $this->tasks()->count();
    }

    public function notes()
    {
        return $this->belongsToMany(Note::class);
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreProjectsRequest;
use App\Models\Client;
use App\Models\Project;
use App\Models\User;
use App\Notifications\ProjectAssignedNotification;
use Illuminate\Support\Facades\Gate;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::with(['user', 'client'])
            ->withCount('tasks')
            ->paginate(20);

        return view('projects.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('manage users');
        $users = User::all();
        $projects = Project::all();
        $clients = Client::all();

        return view('projects.create', compact('users', 'projects', 'clients'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreProjectsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProjectsRequest $request)
    {
        $this->authorize('manage users');
        $project = Project::create($request->validated());

        $user = User::find($request->user_id);

        $user->notify(new ProjectAssignedNotification($project));

        //Mail::to($user)->send(new AssignedProject($project));

        return redirect()->route('projects.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Projects  $projects
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        Gate::authorize('access-projects', $project);

        $project->load('tasks');
        
        return view('projects.show', compact('project'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Projects  $projects
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        Gate::authorize('access-projects', $project);

        $users = User::all();
        $clients = Client::all();

        return view('projects.edit', compact('project', 'users', 'clients'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateProjectsRequest  $request
     * @param  \App\Models\Projects  $projects
     * @return \Illuminate\Http\Response
     */
    public function update(StoreProjectsRequest $request, Project $project)
    {
        Gate::authorize('access-projects', $project);

        $project->update($request->validated());

        return redirect()->route('projects.index')->banner('Project updated successfully.');        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Projects  $projects
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        Gate::authorize('access-projects', $project);

        $project->delete();

        return redirect()->route('projects.index')->dangerBanner('Project deleted successfully.');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/projects/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Project') }}
        </h2>
    </x-slot>

    @role('admin')
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="p-6">

                    <form method="POST" action="{{ route('projects.store') }}">
                        @csrf
                        <div class="space-y-6">

                            {{-- Title --}}
                            <div>
                                <x-jet-label for="title" value="{{ __('Title') }}" />
                                <x-jet-input id="title" class="block w-full mt-1" type="text" name="title" :value="old('title')" autofocus autocomplete="title" />
                                <x-jet-input-error for="title" class="mt-2" />
                            </div>

                            {{-- Body --}}
                            <div>
                                <x-jet-label for="description" value="{{ __('Description') }}" />
                                <x-textarea name="description" id="description" rows="6" class="block w-full mt-1"></x-textarea>
                                <x-jet-input-error for="description" class="mt-2" />
                            </div>

                            {{-- Schedule --}}
                            <div>
                                <x-jet-label for="deadline_at" value="{{ __('Deadline') }}" />
                                <x-pikaday name="deadline_at" format="YYYY-MM-DD" />
                                <x-jet-input-error for="deadline_at" class="mt-2" />
                            </div>

                            {{-- Category --}}
                            <div>
                                <x-jet-label for="user_id" value="{{ __('Assigned user') }}" />
                                <select name="user_id" id="user_id" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">

                                    <option value="">Please select a user</option>
                                    @foreach ($users as $user)
                                        <option value="{{ $user->id }}">{{ $user->name }}</option>
                                    @endforeach
                                </select>
                                <x-jet-input-error for="user_id" class="mt-2" />
                            </div>

                            {{-- Category --}}
                            <div>
                                <x-jet-label for="client_id" value="{{ __('Assigned client') }}" />
                                <select name="client_id" id="client_id" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">

                                    <option value="">Please select a client</option>
                                    @foreach ($clients as $client)
                                        <option value="{{ $client->id }}">{{ $client->name }}</option>
                                    @endforeach
                                </select>
                                <x-jet-input-error for="client_id" class="mt-2" />
                            </div>

                            {{-- Category --}}
                            <div>
                                <x-jet-label for="status" value="{{ __('Status') }}" />
                                <select name="status" id="status" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">

                                    <option value="">Please select a status</option>
                                    @foreach (App\Models\Project::STATUS as $status)
                                        <option
                                            value="{{ $status }}" {{ old('status') == $status ? 'selected' : '' }}>{{ ucfirst($status) }}</option>
                                    @endforeach
                                </select>
                                <x-jet-input-error for="status" class="mt-2" />
                            </div>

                        </div>

                        <div class="flex justify-end mt-6">
                            <x-jet-button>
                                {{ __('Create') }}
                            </x-jet-button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
    @endrole
</x-app-layout>

resources/views/projects/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Project') }}
        </h2>
    </x-slot>

    @can('access-projects', $project)
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="p-6">

                    <form method="POST" action="{{ route('projects.update', $project) }}">
                        @csrf
                        @method('PUT')
                        <div class="space-y-6">

                            {{-- Title --}}
                            <div>
                                <x-jet-label for="title" value="{{ __('Title') }}" />
                                <x-jet-input id="title" class="block w-full mt-1" type="text" name="title" :value="$project->title" autofocus autocomplete="title" />
                                <x-jet-input-error for="title" class="mt-2" />
                            </div>

                            {{-- Body --}}
                            <div>
                                <x-jet-label for="description" value="{{ __('Description') }}" />
                                <x-textarea name="description" id="description" rows="6" class="block w-full mt-1">{{ $project->description }}</x-textarea>
                                <x-jet-input-error for="description" class="mt-2" />
                            </div>

                            {{-- Schedule --}}
                            <div>
                                <x-jet-label for="deadline_at" value="{{ __('Deadline') }}" />
                                <x-pikaday name="deadline_at" format="YYYY-MM-DD" value="{{ $project->deadline_at }}" />
                                <x-jet-input-error for="deadline_at" class="mt-2" />
                            </div>

                            {{-- Category --}}
                            <div>
                                <x-jet-label for="user_id" value="{{ __('Assigned user') }}" />
                                <select name="user_id" id="user_id" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">

                                    <option value="">Please select a user</option>
                                    @foreach ($users as $user)
                                        <option value="{{ $user->id }}"
                                            @if($project->user->id == $user->id)
                                                selected
                                            @endif>{{ $user->name }}</option>
                                    @endforeach
                                </select>
                                <x-jet-input-error for="user_id" class="mt-2" />
                            </div>

                            {{-- Category --}}
                            <div>
                                <x-jet-label for="client_id" value="{{ __('Assigned client') }}" />
                                <select name="client_id" id="client_id" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">

                                    <option value="">Please select a client</option>
                                    @foreach ($clients as $client)
                                        <option value="{{ $client->id }}"
                                            @if($project->client->id == $user->id)
                                                selected
                                            @endif>{{ $client->name }}</option>
                                    @endforeach
                                </select>
                                <x-jet-input-error for="client_id" class="mt-2" />
                            </div>

                            {{-- Category --}}
                            <div>
                                <x-jet-label for="status" value="{{ __('Status') }}" />
                                <select name="status" id="status" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">

                                    <option value="">Please select a status</option>
                                    @foreach (App\Models\Project::STATUS as $status)
                                        <option
                                            value="{{ $status }}" {{ old('status') == $status ? 'selected' : '' }}>{{ ucfirst($status) }}</option>
                                    @endforeach
                                </select>
                                <x-jet-input-error for="status" class="mt-2" />
                            </div>

                        </div>

                        <div class="flex justify-end mt-6">
                            <x-jet-button>
                                {{ __('Update') }}
                            </x-jet-button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
    @endcan
</x-app-layout>

resources/views/projects/index.blade.php
<x-app-layout>
    <div class="py-3">

        @role('admin')
        <div class="mb-3 ml-8">
            <x-jet-secondary-button class="bg-green-700 text-gray-300 hover:text-white hover:bg-green-900">
                <a href="{{ route('projects.create') }}">{{ __('New Project') }}</a>
            </x-jet-secondary-button>
        </div>
        @endrole

        @if(session('message'))
            <div class="mb-4 bg-green-200 p-2 mt-2">
                {{ session('message') }}
            </div>
        @endif
        
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-700">
                    <thead class="bg-gray-200">
                        <tr>
                            <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-grey-light">
                                {{ __('Title') }}
                            </th>
                            <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-grey-light">
                                {{ __('Assinged to') }}
                            </th>
                            <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-grey-light">
                                
                            </th>
                            <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-grey-light">
                                {{ __('Deadline') }}
                            </th>
                            <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-grey-light">
                                {{ __('Tasks') }}
                            </th>
                            <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-grey-light">
                                {{ __('Status') }}
                            </th>
                            <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-grey-light">
                                {{ __('Actions') }}
                            </th>
                        </tr>
                    </thead>
                    <tbody class="bg-white">
                        @foreach ($projects as $project)
                            <tr>
                                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-900 border-b border-grey-light">
                                    <a href="{{ route('projects.show', $project) }}" class="no-underline">
                                        {{ $project->title }}</a>
                                </td>
                                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-900 border-b border-grey-light">
                                    {{ $project->user->name }}
                                </td>
                                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-900 border-b border-grey-light">
                                    {{ $project->client->name }}
                                </td>
                                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-500 border-b border-grey-light">
                                    {{ $project->deadline_at->format('d-m-Y') }}
                                </td>
                                <td class="p-4 whitespace-nowrap text-sm font-semibold text-gray-900 border-b border-grey-light">
                                    {{ $project->completed_tasks }}/{{ $project->tasks_count }}
                                </td>
                                <td class="p-4 whitespace-nowrap text-sm font-semibold text-gray-900 border-b border-grey-light">
                                    {{ $project->status }}
                                </td>
                                <td class="p-4 whitespace-nowrap text-sm font-semibold text-gray-900 border-b border-grey-light">
                                    <div class="flex gap-2 justify-items-start">
                                        @can('access-projects', $project)
                                            <x-jet-secondary-button class="bg-yellow-400 text-gray-600 hover:text-black hover:bg-yellow-500">
                                                <a href="{{ route('projects.edit', $project) }}">{{ __('Edit') }}</a>
                                            </x-jet-secondary-button>
                                                                        
                                            <form method="POST" action="{{ route('projects.destroy', $project) }}">
                                                @csrf
                                                @method('DELETE')
                                                <x-jet-secondary-button type="submit" onclick="return confirm('Are you sure?')" class="bg-red-500 text-gray-800 hover:text-black hover:bg-red-600 inline-block">
                                                    {{ __('Delete') }}
                                                </x-jet-secondary-button>
                                            </form>                                      
                                        @endcan
                                    </div>
                                </td>
                            </tr>  
                        @endforeach 
                    </tbody>
                </table>
            </div>
            <div class="mt-2">
                {{ $projects->links() }}
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/projects/show.blade.php
<x-app-layout>

    @can('access-projects', $project)
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-gray-200 overflow-hidden shadow-xl sm:rounded-lg">
                <div class="container px-6 py-10 mx-auto">
                    <h1 class="text-3xl font-semibold capitalize lg:text-4xl dark:text-gray-700">{{ $project->title }}</h1>
                    
                    <p class="mt-4 xl:mt-6 dark:text-gray-500">
                        {{ Str::words($project->description, 50) }}
                    </p>
                    <div class="grid grid-cols-1 gap-8 mt-8 xl:mt-12 xl:gap-12 md:grid-cols-2 xl:grid-cols-3">
                        @forelse($project->tasks as $task)
                        <div class="p-8 space-y-3 border-2 dark:border-blue-400 rounded-xl">
                            <span class="inline-block dark:text-blue-500">
                                <x-fluentui-task-list-square-rtl-24 class="h-12 w-12"/>
                            </span>
    
                            <h1 class="text-2xl font-semibold capitalize dark:text-gray-700">{{ $task->title }}</h1>
    
                            <p class="dark:text-gray-500">
                                {{ $task->description }}
                            </p>
                            <livewire:completed-task :task="$task">
                        </div> 
                        @empty
                            There are no tasks.
                        @endforelse  

                        <div class="p-8 space-y-3 border-2 dark:border-blue-400 rounded-xl">
                                
                            <button onclick='Livewire.emit("openModal", "create-task", {{ json_encode([$project]) }})' class="dark:text-blue-500">
                                <x-fluentui-task-list-square-add-24-o class="h-12 w-12 justify-center"/>
                                <strong>New Task</strong> 
                            </button>
                        </div>                          
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endcan
</x-app-layout>