routes/web.php
<?php

use App\Http\Controllers\Admin\AdminCalendarController;
use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\User\CalendarController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\User\SavedTaskController;
use App\Http\Controllers\User\UserDashboardController;
use App\Http\Livewire\CompletedTask;
use App\Http\Livewire\User\SavedTasks;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group(['middleware' => 'auth'], function(){

    Route::get('redirects', [HomeController::class, 'index']);

    Route::group(['middleware' => ['role:admin'], 'prefix' => 'admin', 'as' => 'admin.'], function(){
        Route::resource('users', UserController::class);
        Route::get('dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');
        Route::get('calendars', [AdminCalendarController::class,  'index'])->name('calendars');
        Route::get('calendarsEvents', [AdminCalendarController::class,  'fetch']);
    });

    Route::group(['middleware' => ['role:user'], 'prefix' => 'user', 'as' => 'user.'], function(){
        Route::get('dashboard', [UserDashboardController::class, 'index'])->name('dashboard');
        Route::get('completed_task', CompletedTask::class);
        Route::get('saved_tasks', [SavedTaskController::class, 'index'])->name('saved_tasks');
        Route::get('calendars', [CalendarController::class,  'index'])->name('calendars');
        Route::get('calendarsEvents', [CalendarController::class,  'fetch']);
    });

    Route::group(['prefix' => 'notifications', 'as' => 'notifications.'], function () {
        Route::post('/{notification}', [NotificationController::class, 'markNotification'])->name('markNotification');
    });

    Route::resources([
        'clients' => ClientController::class,
        'projects' => ProjectController::class,
        'tasks' => TaskController::class,
    ]);

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    public function projects()
    {
        return $this->hasMany(Project::class);
    }

    public function savedTasks()
    {
        return $this->belongsToMany(Task::class);
    }

    public function notes()
    {
        return $this->hasMany(Note::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserUpdateRequest;
use App\Models\User;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('manage users');
        
        $users = User::withCount('projects')->paginate(20);
        $users->load('roles');
        
        return view('users.index', compact('users'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Users  $users
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $this->authorize('manage users');

        $roles = Role::all();

        return view('users.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UserUpdateRequest  $request
     * @param  \App\Models\Users  $users
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, User $user)
    {
        $this->authorize('manage users');

        $user->update($request->validated());

        $roles = $request->input('roles');

        $user->syncRoles($roles);

        return redirect()->route('users.index');  
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Users $users
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $this->authorize('manage users');
        
        $user->delete();

        return redirect()->route('users.index');
    }
}

app/Http/Controllers/User/CalendarController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Project;
use Illuminate\Http\Request;

class CalendarController extends Controller
{
    public function index()
    {
        return view('user.calendars.index');
    }

    public function fetch()
    {
        $events = Project::selectRaw('title as title, deadline_at as start')
            ->where('user_id', auth()->id())
            ->get();

        return response()->json($events);
    }
}

app/Http/Controllers/User/SavedTaskController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Task;
use Illuminate\Http\Request;

class SavedTaskController extends Controller
{
    public function index()
    {
        $tasks = Task::whereHas('savedUsers', function($query){
            $query->where('id', auth()->id());
        })->get();

        return view('user.tasks.saved', compact('tasks'));
    }
}

app/Http/Controllers/User/UserDashboardController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Project;

class UserDashboardController extends Controller
{
    public function index()
    {        
        return view('user.dashboard.index');
    }
}

app/Http/Livewire/User/SavedTasksCount.php
<?php

namespace App\Http\Livewire\User;

use App\Models\Task;
use Livewire\Component;

class SavedTasksCount extends Component
{
    protected $listeners = ['taskSaved' => 'render'];
    
    public function render()
    {
        $savedAmount = auth()->user()->savedTasks()->count();

        return view('livewire.user.saved-tasks-count', compact('savedAmount'));
    }
}

app/Http/Livewire/User/UserDashboard.php
<?php

namespace App\Http\Livewire\User;

use App\Models\Project;
use App\Models\Task;
use Livewire\Component;

class UserDashboard extends Component
{
    public $taskId;

    protected $listeners = ['taskCompleted' => 'render'];

    public function toggleTask($taskId)
    {
        $task = Task::find($taskId);

        $task->completed = !$task->completed;

        $task->save();

        $this->emit('taskCompleted');
    }

    public function saveTask($taskId)
    {
        auth()->user()->savedTasks()->attach($taskId);

        $this->emit('taskSaved');
    }

    public function unsaveTask($taskId)
    {
        auth()->user()->savedTasks()->detach($taskId);

        $this->emit('taskSaved');
    }

    public function render()
    {
        $projects = Project::withCount('tasks')
            ->where('user_id', auth()->id())
            ->get();

        return view('livewire.user.user-dashboard', compact('projects'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/users/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Update user') }}
        </h2>
    </x-slot>

    @hasrole('admin')
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 m-3">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="p-6">

                    <form method="POST" action="{{ route('admin.users.update', $user) }}">
                        @csrf
                        @method('PUT')
                        
                        <div class="space-y-6">
                            <!-- Name -->
                            <div class="mb-3">
                                <x-jet-label for="name" value="{{ __('Name') }}" />
                                <x-jet-input id="name" class="block w-full mt-1" type="text" name="name" :value="$user->name" autofocus autocomplete="name" />
                                <x-jet-input-error for="name" class="mt-2" />
                            </div>
                
                            <!-- Email -->
                            <div class="mb-3">
                                <x-jet-label for="email" value="{{ __('Email') }}" />
                                <x-jet-input id="email" class="block w-full mt-1" type="text" name="email" :value="$user->email" autofocus autocomplete="email" />
                                <x-jet-input-error for="email" class="mt-2" />
                            </div>
                            
                            <!-- Role -->
                            <div class="mb-3">
                                <x-jet-label for="roles" value="{{ __('Role') }}" />
                                <select name="roles" id="roles" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">

                                    <option value="">Please select a role</option>
                                    @foreach ($roles as $id => $roles)
                                        <option 
                                            >{{ $roles->name }}</option>
                                    @endforeach
                                </select>
                                <x-jet-input-error for="roles" class="mt-2" />
                            </div>
                
                            <div class="flex justify-end mb-6">
                                <x-jet-button>
                                    {{ __('Update') }}
                                </x-jet-button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
    @endhasrole
</x-app-layout>

resources/views/users/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('User Management') }}
        </h2>
    </x-slot>
    @can('manage users')
        {{-- Users table --}}
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <table class="text-left w-full border-collapse"> <!--Border collapse doesn't work on this site yet but it's available in newer tailwind versions -->
                    <thead>
                    <tr>
                        <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">#</th>
                        <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Name</th>
                        <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Email</th>
                        <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Nr of Projects</th>
                        <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Role</th>
                        <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                        @forelse ($users as $key=>$user)
                            <tr class="hover:bg-grey-lighter">
                                <td class="py-4 px-6 border-b border-grey-light">{{ $key+1 }}</td>
                                <td class="py-4 px-6 border-b border-grey-light">{{ $user->name }}</td>
                                <td class="py-4 px-6 border-b border-grey-light">{{ $user->email}}</td>
                                <td class="py-4 px-6 border-b border-grey-light">{{ $user->projects_count }}</td>
                                @foreach($user->roles()->pluck('name') as $role)
                                    <td class="py-4 px-6 border-b border-grey-light">{{ $role }}</td>
                                @endforeach                               
                                <td class="py-4 px-6 border-b border-grey-light justify-center">   
                                    <div class="flex gap-2">
                                        <x-jet-secondary-button class="bg-yellow-400 text-gray-600 hover:text-black hover:bg-yellow-500">
                                            <a href="{{ route('admin.users.edit', $user) }}">{{ __('Edit') }}</a>
                                        </x-jet-secondary-button>
                                        
                                        <form method="POST" action="{{ route('admin.users.destroy', $user) }}">
                                            @csrf
                                            @method('DELETE')
                                            <x-jet-secondary-button type="submit" onclick="return confirm('Are you sure?')" class="bg-red-500 text-gray-800 hover:text-black hover:bg-red-600 inline-block">
                                                {{ __('Delete') }}
                                            </x-jet-secondary-button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @empty
                            There are no users
                        @endforelse                          
                    </tbody>
                </table>  
            </div>
            <div class="mt-2">
                {{ $users->links() }}
            </div>
        </div>
    </div>
    @endcan
</x-app-layout>