routes/web.php
<?php

use App\Http\Controllers\Admin\AdminCalendarController;
use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\User\CalendarController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\User\SavedTaskController;
use App\Http\Controllers\User\UserDashboardController;
use App\Http\Livewire\CompletedTask;
use App\Http\Livewire\User\SavedTasks;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group(['middleware' => 'auth'], function(){

    Route::get('redirects', [HomeController::class, 'index']);

    Route::group(['middleware' => ['role:admin'], 'prefix' => 'admin', 'as' => 'admin.'], function(){
        Route::resource('users', UserController::class);
        Route::get('dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');
        Route::get('calendars', [AdminCalendarController::class,  'index'])->name('calendars');
        Route::get('calendarsEvents', [AdminCalendarController::class,  'fetch']);
    });

    Route::group(['middleware' => ['role:user'], 'prefix' => 'user', 'as' => 'user.'], function(){
        Route::get('dashboard', [UserDashboardController::class, 'index'])->name('dashboard');
        Route::get('completed_task', CompletedTask::class);
        Route::get('saved_tasks', [SavedTaskController::class, 'index'])->name('saved_tasks');
        Route::get('calendars', [CalendarController::class,  'index'])->name('calendars');
        Route::get('calendarsEvents', [CalendarController::class,  'fetch']);
    });

    Route::group(['prefix' => 'notifications', 'as' => 'notifications.'], function () {
        Route::post('/{notification}', [NotificationController::class, 'markNotification'])->name('markNotification');
    });

    Route::resources([
        'clients' => ClientController::class,
        'projects' => ProjectController::class,
        'tasks' => TaskController::class,
    ]);

});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Client extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'name',
        'vat_number',
        'address',
        'country_code',
        'zip_code',
    ];

    public function projects()
    {
        return $this->hasMany(Project::class);
    }

    public function getFullAddressAttribute()
    {
        return $this->address . ' , ' .$this->country_code . '  ' .$this->zip_code;
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreClientsRequest;
use App\Models\Client;
use Illuminate\Support\Facades\Gate;

class ClientController extends Controller
{
    public function index()
    {
        $clients = Client::paginate(20);

        return view('clients.index', compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('manage users');

        return view('clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreClientsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreClientsRequest $request)
    {
        $this->authorize('manage users');

        Client::create($request->validated());

        return redirect()->route('clients.index')->banner('Client created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        $this->authorize('manage users');

        return view('clients.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(StoreClientsRequest $request, Client $client)
    {
        $this->authorize('manage users');

        $client->update($request->validated());

        return redirect()->route('clients.index')->banner('Client updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        $this->authorize('manage users');
        
        $client->delete();

        return redirect()->route('clients.index')->dangerBanner('Client deleted successfully.');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/clients/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Client') }}
        </h2>
    </x-slot>
    
    @role('admin')
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                
                <div class="p-6">
                    <form method="POST" action="{{ route('clients.store') }}">
                        @csrf

                        <div class="space-y-6">
                            <!-- Company Name -->
                            <div class="mb-3">
                                <x-jet-label for="name" value="{{ __('Company Name') }}" />
                                <x-jet-input id="name" class="block w-full mt-1" type="text" name="name" :value="old('name')" autofocus autocomplete="name" />
                                <x-jet-input-error for="name" class="mt-2" />
                            </div>
                
                            <!-- Vat -->
                            <div class="mb-3">
                                <x-jet-label for="vat_number" value="{{ __('Vat Number') }}" />
                                <x-jet-input id="vat_number" class="block w-full mt-1" type="text" name="vat_number" :value="old('vat_number')" autofocus autocomplete="vat_number" />
                                <x-jet-input-error for="vat_number" class="mt-2" />
                            </div>

                            <!-- Address -->
                            <div class="mb-3">
                                <x-jet-label for="address" value="{{ __('Address') }}" />
                                <x-jet-input id="address" class="block w-full mt-1" type="text" name="address" :value="old('address')" autofocus autocomplete="address" />
                                <x-jet-input-error for="address" class="mt-2" />
                            </div>
                            
                             <!-- Countru code -->
                             <div class="mb-3">
                                <x-jet-label for="country_code" value="{{ __('Country Code') }}" />
                                <x-jet-input id="country_code" class="block w-full mt-1" type="text" name="country_code" :value="old('country_code')" autofocus autocomplete="country_code" />
                                <x-jet-input-error for="country_code" class="mt-2" />
                            </div>

                            <!-- Zip Code -->
                            <div class="mb-3">
                                <x-jet-label for="zip_code" value="{{ __('Zip Code') }}" />
                                <x-jet-input id="zip_code" class="block w-full mt-1" type="text" name="zip_code" :value="old('zip_code')" autofocus autocomplete="zip_code" />
                                <x-jet-input-error for="zip_code" class="mt-2" />
                            </div>
                
                            <div class="flex justify-end mt-6">
                                <x-jet-button>
                                    {{ __('Create') }}
                                </x-jet-button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @endrole
</x-app-layout>

resources/views/clients/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit Client') }}
        </h2>
    </x-slot>
    
    @role('admin')
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                
                <div class="p-6">
                    <form method="POST" action="{{ route('clients.update', $client) }}">
                        @csrf
                        @method('PUT')

                        <div class="space-y-6">
                            <!-- Company Name -->
                            <div class="mb-3">
                                <x-jet-label for="name" value="{{ __('Company Name') }}" />
                                <x-jet-input id="name" class="block w-full mt-1" type="text" name="name" :value="$client->name" autofocus autocomplete="name" />
                                <x-jet-input-error for="name" class="mt-2" />
                            </div>
                
                            <!-- Vat -->
                            <div class="mb-3">
                                <x-jet-label for="vat_number" value="{{ __('Vat Number') }}" />
                                <x-jet-input id="vat_number" class="block w-full mt-1" type="text" name="vat_number" :value="$client->vat_number" autofocus autocomplete="vat_number" />
                                <x-jet-input-error for="vat_number" class="mt-2" />
                            </div>

                            <!-- Address -->
                            <div class="mb-3">
                                <x-jet-label for="address" value="{{ __('Address') }}" />
                                <x-jet-input id="address" class="block w-full mt-1" type="text" name="address" :value="$client->address" autofocus autocomplete="address" />
                                <x-jet-input-error for="address" class="mt-2" />
                            </div>
                            
                             <!-- Countru code -->
                             <div class="mb-3">
                                <x-jet-label for="country_code" value="{{ __('Country Code') }}" />
                                <x-jet-input id="country_code" class="block w-full mt-1" type="text" name="country_code" :value="$client->country_code" autofocus autocomplete="country_code" />
                                <x-jet-input-error for="country_code" class="mt-2" />
                            </div>

                            <!-- Zip Code -->
                            <div class="mb-3">
                                <x-jet-label for="zip_code" value="{{ __('Zip Code') }}" />
                                <x-jet-input id="zip_code" class="block w-full mt-1" type="text" name="zip_code" :value="$client->zip_code" autofocus autocomplete="zip_code" />
                                <x-jet-input-error for="zip_code" class="mt-2" />
                            </div>
                
                            <div class="flex justify-end mt-6">
                                <x-jet-button>
                                    {{ __('Update') }}
                                </x-jet-button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @endrole
</x-app-layout>

resources/views/clients/index.blade.php
<x-app-layout>
  
    <div class="py-3">
        @role('admin')
        <div class="mb-3 ml-8">
            <x-jet-secondary-button class="bg-green-700 text-gray-300 hover:text-white hover:bg-green-900">
                <a href="{{ route('clients.create') }}">{{ __('Add Client') }}</a>
            </x-jet-secondary-button>
        </div>
        @endrole

        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-700">
                    <thead class="bg-gray-200">
                        <tr>
                            <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-grey-light">
                            {{ __('Company') }}
                            </th>
                            <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-grey-light">
                            {{ __('Vat') }}
                            </th>
                            <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-grey-light">
                            {{ __('Address') }}
                            </th>
                            <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-grey-light">
                                {{ __('Actions') }}
                            </th>
                        </tr>
                    </thead>
                    <tbody class="bg-white">
                        @foreach ($clients as $client)
                            <tr>
                                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-900 border-b border-grey-light">
                                    {{ $client->name }}
                                </td>
                                <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-500 border-b border-grey-light">
                                    {{ $client->vat_number }}
                                </td>
                                <td class="p-4 whitespace-nowrap text-sm font-semibold text-gray-900 border-b border-grey-light">
                                    {{ $client->full_address }}
                                </td>
                                @role('admin')
                                <td class="p-4 whitespace-nowrap text-sm font-semibold text-gray-900 border-b border-grey-light">
                                    <div class="flex gap-2 justify-items-start">
                                        <x-jet-secondary-button class="bg-yellow-400 text-gray-600 hover:text-black hover:bg-yellow-500">
                                            <a href="{{ route('clients.edit', $client) }}">{{ __('Edit') }}</a>
                                        </x-jet-secondary-button>

                                        <form method="POST" action="{{ route('clients.destroy', $client) }}">
                                            @csrf
                                            @method('DELETE')
                                            <x-jet-secondary-button type="submit" onclick="return confirm('Are you sure?')" class="bg-red-500 text-gray-800 hover:text-black hover:bg-red-600 inline-block">
                                                {{ __('Delete') }}
                                            </x-jet-secondary-button>
                                        </form>
                                    </div>
                                </td>
                                @endrole
                            </tr>  
                        @endforeach 
                    </tbody>
                </table>
            </div>
            <div class="mt-2">
                {{ $clients->links() }}
            </div>
        </div>
    </div>
</x-app-layout>